{% set name = "crossenv" %}
{% set version = "1.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/crossenv-{{ version }}.tar.gz
  sha256: 0631d4f93d58c63d53d4fa8a016de63a28312cc0afdd1c663ed61f6cc026c0ec
  patches:
    - patches/0002-Fix-py38-support.patch
    - patches/gh119.patch

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools
  run:
    - python >=3.8

test:
  imports:
    - crossenv
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/benfogle/crossenv
  summary: A cross-compiling tool for Python extension modules
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - chrisburr
    - isuruf
