{% set name = "crossenv" %}
{% set version = "1.1.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/crossenv-{{ version }}.tar.gz
  sha256: e15e47a004f2725089601afb58141a48b6b4fa907c041d54ec884d829f4309ea

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.4
  run:
    - python >=3.4

test:
  imports:
    - crossenv
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/benfogle/crossenv
  summary: A cross-compiling tool for Python extension modules
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - isuruf
