{% set name = "crossenv" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/crossenv-{{ version }}.tar.gz
  sha256: 445f68f2c001d00730439e855adc898f62df17264edbda232027050b8a213b1f
  patches:
    - patches/0002-Fix-py38-support.patch
    - patches/gh86.patch
    - patches/gh91.patch
    - patches/gh92.patch
    - patches/gh94.patch
    - patches/gh95.patch
    - patches/gh96.patch

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.4
  run:
    - python >=3.4

test:
  imports:
    - crossenv
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/benfogle/crossenv
  summary: A cross-compiling tool for Python extension modules
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - isuruf
