schema_version: 1

context:
  name: crossenv
  version: 1.6.1

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/crossenv-${{ version }}.tar.gz
  sha256: 5b7e2f231d9a3c6ea56ce3b7fd7acbe0f1e310e44a8f699909910f1334db1a31
  patches:
    # - patches/0002-Fix-py38-support.patch # drop that one atm
    # - patches/gh121.patch
    # - patches/gh130.patch

build:
  number: 3
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - crossenv
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - pip check

about:
  summary: A cross-compiling tool for Python extension modules
  license: MIT
  license_file: LICENSE.txt
  homepage: https://github.com/benfogle/crossenv

extra:
  recipe-maintainers:
    - chrisburr
    - isuruf
